version: "3.8"
services:
  net-automation:
    build: .
    container_name: net-automation
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./inspect_report:/app/inspect_report
    restart: always  # 容器异常退出自动重启