#巡检配置
inspect:
  interval: 3600
  check_items: ["interface_status",
  "vlan_status",
  "cpu_usage",
  "memory_usage"]
  warn_threshold:
    cpu_usage: 80
    memory_usage: 85
    interface_status: 1
#日志配置
log:
  path: "./logs/"
  level: "INFO"
#web配置
web:
  host: "0.0.0.0"
  port: 5000

